---
title: "Prediction models to classify survivors from nonsurvivors of sepsis (raw data) using logistic regression, for samples greater than D1"
author: "Thanneer Perumal"
date: '`r date()`'
output: html_document
---
  
```{r knit2synapse, eval = FALSE, include=FALSE}
## It is assumed your working directory is where this file is
library(synapseClient)
library(githubr)
library(knitr)
library(knit2synapse)

synapseLogin()

knit2synapse::storeAndKnitToFileEntity(file = 'FinalLogRegPredictionModelsRaw_FutureSamples.Rmd',
                                       parentId = 'syn5909391',
                                       entityName = 'Final Logistic Regression Predictions (predictions greater than D1)')
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE, cache = FALSE}
## It is assumed your working directory is where this file is

# Clear R console screen output
cat("\014")  

# Load required libraries
library(CovariateAnalysis)
library(data.table)
library(tidyr)
library(plyr)
library(dplyr)
library(stringr)

library(RColorBrewer)
library(ggplot2)

library(parallel)
library(glmnet)
library(ranger)
library(ROCR)
library(WGCNA)

library(limma)
library(sva)
library(RankProd)
library(pracma)

library(doParallel)
library(foreach)

cl = makeCluster(2)
registerDoParallel(cl)

options(xtable.type="html")

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = FALSE)
```

```{r synapseParams, include=FALSE}
parentId ="syn6175515"

ActivityName <- 'Classification analysis'

thisFileName <- 'FinalLogRegPredictionModelsRaw_FutureSamples.Rmd'

# Github link
thisRepo <- getRepo(repository = "th1vairam/Sepsis_Metaanalysis", 
                    ref="branch", 
                    refName='classify')

thisFile <- getPermlink(repository = thisRepo,
                        repositoryPath=paste0('code/Rmd/', thisFileName))
```

```{r coallateData}
metadata.id = 'syn6039077'
all.used.id = metadata.id
metadata = read.csv(synGet(metadata.id)@filePath)
metadata$outcomes = factor(metadata$outcomes, c('survivor', 'nonsurvivor'))

# Scale severity scores for each study
metadata = (metadata %>% ddply(.(Study), .fun = function(x){x$severity = scale(x$severity); return(x)}))
metadata$severity = as.numeric(metadata$severity)
rownames(metadata) = metadata$GSM
  
expr.id = 'syn6039081'
all.used.id = c(all.used.id, expr.id)
expr = readRDS(synGet(expr.id)@filePath)

# Remove duplicated genes
tmp.expr = dplyr::select(expr, -Symbol)
rownames(tmp.expr) = paste('Genes', 1:dim(tmp.expr)[1], sep = '')
tmp.expr = WGCNA::collapseRows(tmp.expr, expr$Symbol, rownames(tmp.expr))$datETcollapsed
expr = tmp.expr
expr[is.na(expr)] = 0
```

```{r train, results='asis'}
# Collect training metadata and expression data
metadata.train = metadata %>%
  filter(Study %in% c('GSE40586', 'GSE10474', 'GSE13015a', 'GSE13015b', 'GSE27131', 
                      'GSE32707', 'GSE63042', 'GSE66099', 'GSE66890', 'EMTAB1548', 
                      'EMEXP3567', 'EMEXP3850'),
         !(GSM %in% c('GSM812705', 'GSM812737', 'GSM812721', 'GSM812696', 'GSM812638'))) %>% # outliers identified from own analysis
  filter(!(GSM %in% c('SL113expII', 'SL136expI', 'SL160expI', 'SL42expII', 'SS54exp2', 'SSd59exp1', 'SSd64exp2', 'SSd69exp2'))) # outliers from internal communication between Tim and Spain group
rownames(metadata.train) = metadata.train$GSM

ind = intersect(rownames(metadata.train), colnames(expr))
metadata.train = metadata.train[ind,]
expr.train = expr[,ind]
rownames(expr.train) = rownames(expr)

writeLines('Training data sets breakup')
tmp = table(droplevels(metadata.train$Study), factor(metadata.train$outcomes, levels = c('survivor', 'nonsurvivor')))
kable(tmp)
```

```{r test, results='asis'}
# Get GSE54514 metadata and expression data
all.used.id = c(all.used.id,'syn5614371','syn5614393','syn5614390')
mtd.gse54514 = downloadFile('syn5614371') %>%
  filter(DiagnosisPrimary == 'Sepsis') %>%
  dplyr::rename(GSM = V1, outcomes = Survivor, severity = APACHE_II, age = Age, days.since.admission = group_day) %>%
  dplyr::select(GSM, outcomes, age, severity, gender, days.since.admission) %>%
  dplyr::mutate(outcomes = factor(outcomes, levels = c('YES','NO'), labels = c('YES' = 'survivor', 'NO' = 'nonsurvivor')),
                gender = factor(gender, levels = c('F', 'M'), labels = c('F' = 'female', 'M' = 'male')))
rownames(mtd.gse54514) = mtd.gse54514$GSM

expr.gse54514 = readRDS(synGet('syn5614393')@filePath)

mapp.gse54514 = readRDS(synGet('syn5614390')@filePath)

expr.gse54514 = collapseRows(expr.gse54514, rowGroup = mapp.gse54514[rownames(expr.gse54514)], rowID = rownames(expr.gse54514))[[1]]

# Get gse21802 metadata and expression data
all.used.id = c(all.used.id,'syn5969255','syn5969254','syn5969256')
mtd.gse21802 = downloadFile('syn5969255') %>%
  filter(DiagnosisPrimary == 'Sepsis') %>%
  dplyr::rename(GSM = V1, severity = APACHE.at.admission, outcomes = SURVIVOR, days.since.admission = Days.since.ICU.admission.at.collection) %>%
  dplyr::mutate(age = 0, gender = NA) %>%
  dplyr::select(GSM, age, severity, outcomes, gender, days.since.admission) %>%
  dplyr::mutate(outcomes = factor(outcomes, c('YES', 'NO'), labels = c('YES' = 'survivor', 'NO' = 'nonsurvivor')))
rownames(mtd.gse21802) = mtd.gse21802$GSM

expr.gse21802 = readRDS(synGet('syn5969254')@filePath)

mapp.gse21802 = readRDS(synGet('syn5969256')@filePath)

expr.gse21802 = collapseRows(expr.gse21802, rowGroup = mapp.gse21802[rownames(expr.gse21802)], rowID = rownames(expr.gse21802))[[1]]

ind = intersect(rownames(expr.gse54514), rownames(expr.gse21802))
expr.test = cbind(expr.gse54514[ind,], expr.gse21802[ind,])

metadata.test = rbindlist(list(GSE54514 = mtd.gse54514, GSE21802 = mtd.gse21802), idcol = 'Study', use.names = T) %>%
  dplyr::mutate(SetName = 'Testing')
rownames(metadata.test) = metadata.test$GSM

ind = intersect(rownames(metadata.test), colnames(expr.test))
expr.test = expr.test[,ind]
metadata.test = metadata.test[ind,]
```

```{r selectGenes}
# Intersect training and testing gene sets
genes = read.table(synGet('syn6156621')@filePath, header=T) %>%
  unlist %>% as.character()

expr.train = expr.train[rownames(expr.train) %in% genes,]
expr.test = expr.test[rownames(expr.test) %in% genes,]

expr.train[is.na(expr.train)] = 0
expr.test[is.na(expr.test)] = 0
```
Performing classification with `r length(genes)` genes in the model

### Performing logistic regression
```{r simulate.lr, results = 'asis'}
features = c("AIM2", "APH1A", "CCR2", "CFD", "DDIT4", "DEFA4", "EIF5A", "GSTM1", "HIST1H3H", "IFI27", "IL1R2",
             "IL8", "MAFF", "NT5E", "OCLN", "RAB40B", "RGS1", "VNN3")

# Get training and testing data
ind = which(rownames(expr.train) %in% features)
x.train = t(expr.train[ind,])
x.train = cbind(data.frame(Study = as.numeric(metadata.train[rownames(x.train),'Study'])),
                x.train) %>%
  data.matrix()
y.train = as.numeric(factor(metadata.train[rownames(x.train), 'outcomes'], c('survivor', 'nonsurvivor')))
names(y.train) = metadata.train[rownames(x.train), 'GSM']
    
# Get second set of testing data (private samples)
metadata.test = as.data.frame(metadata.test)
rownames(metadata.test) = gsub('-','_',metadata.test$GSM)

ind = which(rownames(expr.test) %in% features)
x.test = t(expr.test[ind,])

x.test = cbind(data.frame(Study = as.numeric(as.factor(metadata.test[rownames(x.test),'Study'])) + max(as.numeric(metadata$Study))),
                x.test) %>%
  data.matrix()
y.test = as.numeric(factor(metadata.test[rownames(x.test), 'outcomes'], c('survivor', 'nonsurvivor')))
names(y.test) = rownames(metadata.test)

# Set penalty factor for coefficients in the model (0 for Study and 1 for all the genes)
pf = rep(1, dim(x.train)[2])
pf[1] = 0
    
# Cross validation fit using penalised logistic regression
fit.cv = cv.glmnet(x.train, y.train, family = "binomial", 
                   type.measure = 'class', parallel =TRUE,
                   penalty.factor = pf)
coeff = as.matrix(coef.glmnet(fit.cv, s = 'lambda.min'))

# Get scores for test data
scores = predict.cv.glmnet(fit.cv, newx = x.test, s = "lambda.min", type = "response")
colnames(scores) = 'nonsurvivor'
rownames(scores) = rownames(x.test)
scores = rownameToFirstColumn(scores, 'GSM') %>%
  list(metadata.test) %>%
  join_all() %>%
  dplyr::mutate(days.since.admission = gsub('NS_D','',days.since.admission),
                days.since.admission = gsub('S_D','',days.since.admission),
                days.since.admission = as.numeric(days.since.admission))

p = ggplot(scores, aes(x = factor(days.since.admission), y = nonsurvivor, color = outcomes)) + geom_boxplot() 
p = p + geom_jitter(position= position_jitterdodge()) + facet_grid(Study~.) + theme(legend.position = 'top')
p

# Write validation scores
scores = filter(scores, 
                (days.since.admission > 1 & Study == 'GSE54514') | 
                  (days.since.admission <= 2 & days.since.admission >= 0 & Study == 'GSE21802')) %>%
  write.table(file = 'validation_scores_ftr_samples_lr.tsv', sep = '\t', row.names = F, quote=F)
obj = File('validation_scores_ftr_samples_lr.tsv', name = 'Validation scores supplement (logistic regression)', parentId = 'syn6175515')
obj = synStore(obj, used = all.used.id, executed = thisFile, activityName = ActivityName)
```

### Use exisiting features to predict serverity
```{r simulate.lr.sev, results = 'asis'}
# Get training and testing data
rownames(metadata) = metadata$GSM
ind = which(rownames(expr.train) %in% features)
x.train = t(expr.train[ind,])
x.train = cbind(data.frame(Study = as.numeric(metadata[rownames(x.train),'Study'])),
                x.train) %>%
  data.matrix()
y.train = as.numeric(metadata[rownames(x.train),'severity'])
names(y.train) = rownames(x.train)
y.train = na.omit(y.train)
x.train = x.train[names(y.train),]

# Get testing data
ind = which(rownames(expr.test) %in% features)
x.test = t(expr.test[ind,])
x.test = cbind(data.frame(Study = as.numeric(as.factor(metadata.test[rownames(x.test),'Study']))),
                x.test) %>%
  data.matrix()
y.test = as.numeric(metadata.test[rownames(x.test),'severity'])
names(y.test) = rownames(x.test)
y.test = na.omit(y.test)
x.test = x.test[names(y.test),]

# Set penalty factor for coefficients in the model (0 for Study and 1 for all the genes)
pf = rep(1, dim(x.train)[2])
pf[1] = 0
    
# Cross validation fit using penalised logistic regression
fit.cv = cv.glmnet(x.train, y.train, family = "gaussian", 
                   parallel =TRUE,
                   penalty.factor = pf)
coeff = as.matrix(coef.glmnet(fit.cv, s = 'lambda.min'))

# Get scores for test data
scores = predict.cv.glmnet(fit.cv, newx = x.test, s = "lambda.min", type = "response")
colnames(scores) = 'nonsurvivor'
rownames(scores) = rownames(x.test)
scores = rownameToFirstColumn(scores, 'GSM') %>%
  list(metadata.test) %>%
  join_all() %>%
  dplyr::mutate(days.since.admission = gsub('NS_D','',days.since.admission),
                days.since.admission = gsub('S_D','',days.since.admission),
                days.since.admission = as.numeric(days.since.admission))

p = ggplot(scores, aes(x = factor(days.since.admission), y = nonsurvivor, color = outcomes)) + geom_boxplot() 
p = p + geom_jitter(position= position_jitterdodge()) + facet_grid(Study~.) + theme(legend.position = 'top')
p

# Write validation scores
scores = filter(scores, 
                (days.since.admission > 1 & Study == 'GSE54514') | 
                  (days.since.admission <= 2 & days.since.admission >= 0 & Study == 'GSE21802')) %>%
  write.table(file = 'validation_scores_ftr_samples_withSeverity_lr.tsv', sep = '\t', row.names = F, quote=F)
obj = File('validation_scores_ftr_samples_withSeverity_lr.tsv', name = 'Validation scores supplement with severity (logistic regression)', parentId = 'syn6175515')
obj = synStore(obj, used = all.used.id, executed = thisFile, activityName = ActivityName)
```